### ISSUE TITLE
Abapy Install issue with Conda

### ISSUE THREAD

**Issue by yyazicio** [lcharleux/abapy#5]
Dear Sir

I have installation issue for your abapy packages.
I have anaconda with py 3 installation..
Steps I followed is first download git repository as zip file.
After in conda shell I run

conda install abapy.zip

all packages are installed. 

When I try to call abapy with import abapy it gives the following error : 

import abapy
Traceback (most recent call last):

  File "<ipython-input-15-5e5865a27792>", line 1, in <module>
    import abapy

  File "C:\Users\zyuce\AppData\Local\Continuum\Anaconda3\lib\site-packages\abapy-0.1-py3.6.egg\abapy\__init__.py", line 56, in <module>
    import indentation, materials, mesh, misc, postproc

ModuleNotFoundError: No module named 'indentation'

Which step may I missing?

**Comment by Spandyie** [comment]
I am getting similar error. I tried installing all packages individually, however. It does not let me install postproc and misc package.

**Comment by Hari-Magara** [comment]
Ensure the following

1. See to that you use Python 2.7.* version. It doesn't work with 3.*
2. Ensure you put the abapy folder in the exact site-package where the python 2.7 is installed.

Hope this helps

**Comment by geosharma** [comment]
My installation is as follows:
ABAQUS 2018
I primarily use Python 3, so I created a Python 2, environment in Conda to install abapy
``conda create --name abapy python=2``
Activated the python 2 abapy environment
``conda activate abapy``
Installed abapy as per the instructions
``pip install git+https://github.com/lcharleux/abapy.git``
Close everything
Now I start the Anaconda Windows10 terminal, Anaconda Prompt 
I move to the directory where I have indentation_axi.inp file, let us call this directory ``foo``, F:\path\to\foo\, I am now in ``foo``
I run the simulation in ABAQUS
``abaqus job=indentation_axi``
Following the tutorial
``abaqus viewer -noGUI`` works fine
In the command prompt
``from odbAccess import openOdb``
``odb = openOdb('indentation_axi.odb')``
All works fine, so continuing with the tutorial
``from odbAccess import openOdb``
``from abapy.misc import dump``
I get error message
```
raceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SMAPython\SMAPytLibPy.m\src\site.py", line 120, in _numpyHook
ImportError: No module named abapy.misc
```
So I quit the ABAQUS python. I am now in conda ``abapy`` environment with Python 2. 
``python``
Returns: Python 2.7.16 ..... 
``from abapy.misc import dump``
Everything fine

``from odbAccess import openOdb``
I get the error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named odbAccess
```
So it seems if I am in conda abapy python 2 environment (python2 shell) I cannot access ABAQUS modules and when I am in ABAQUS python shell I cannot access abapy modules.

I would greatly appreciate any help, thanks. Also, if it is not too troublesome, a step by step procedure would be of great help for future users too. Sorry for reposting to this old issue and thanks once again.

**Comment by CsatiZoltan** [comment]
```
ModuleNotFoundError: No module named 'indentation'
```
Same error when installed with `pip`. Note that this error happens with Python 3 only, as this project is not compatible with Python 3. Since Abaqus comes with Python 2, and because *abapy* provides functionalities that are available only when executed from within Abaqus Python, *abapy* must not use any Python 3 specific code. What I recommend is forking this project, as its development seems to have stalled, and make it Python 3 compatible (without losing its compatibility with Python 2, as explained above).

@geosharma 
> So it seems if I am in conda abapy python 2 environment (python2 shell) I cannot access ABAQUS modules

That is expected. Abaqus modules can only be used from within the embedded Python interpreter that comes with Abaqus: `ImportError: abaqus module may only be imported in the Abaqus kernel process`

> when I am in ABAQUS python shell I cannot access abapy modules.

Because you installed it for your conda environment. The way I solved it is [copying](https://github.com/lcharleux/abapy/issues/1#issuecomment-181709696) the `abapy` directory to the site-packages directory of Abaqus Python. A better way is to set up `'PYTHONPATH'` for Abaqus Python, as explained [here](https://github.com/lcharleux/abapy/issues/1#issuecomment-181434338).

These were more detailed explanations what were already given by [Hari-Magara](https://github.com/lcharleux/abapy/issues/5#issuecomment-384589743).
